/*
 * (C) Copyright 2021 Nuxeo (http://nuxeo.com/) and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *     Michael Vachette
 */

package org.nuxeo.labs.download.link.service;

import org.nuxeo.ecm.core.api.DocumentModel;

public interface PublicDownloadLinkBuilder {

    /**
     * Build a public download link
     * @param doc
     * @param xpath the xpath of the file
     * @return a url
     */
    String getPublicDownloadLink(DocumentModel doc, String xpath, String token);

    /**
     * Notify that download permission for the link was revoked
     * @param doc
     * @param xpath the xpath of the file
     * @param link the link generated by the getPublicDownloadLLink method
     */
    void publicDownloadPermissionRevoked(DocumentModel doc, String xpath, String link);


}
